### ISSUE TITLE
Undefined symbol _OBJC_CLASS_$_SFGeometryUtils

### ISSUE THREAD

**Issue by rdkgit** [ngageoint/mgrs-ios#2]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * MGRS iOS Version:  1.1.4
  * MGRS iOS Source: (e.g. CocoaPods, Source Code Build) CocaPods
  * CocoaPods Version: 1.12.1
  * Xcode Version:  14.3
  * Device or Emulator: ipad air 2023 
  * iOS Version: 16.4.1
  * Other Relevant Libraries: 

#### Expected Results:

  * What did you expect to happen?  Built just fine until did a build clean; upgraded macbook to 13.3.1 but not sure this is related.

#### Observed Results:

  * What happened instead?  Build/link fails.
  * How often does this occur?  Every time.

#### Output:

  * Any logs, errors, or output messages?  See screen snapshot

#### Steps to Reproduce:

  1. Step One
  2. Step Two
  3. ...

#### Relevant Code:

```swift
// Code to reproduce the problem?
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?
![Screenshot from 2023-05-09 16-49-12](https://github.com/ngageoint/mgrs-ios/assets/3226880/236475d6-0496-4eaa-8040-17419b0367de)

**Comment by rdkgit** [comment]
This is an iPad Air 5th generation with 16.4.1 (a) which is 16.4.1 with rapid security response (a) installed. If I do a clean build on any other 16.4 simulators, I get same build/link error with mgrs-ios SFGeometryUtils undefined symbol.  I've tried re-installing cocoa pods via command-line but no luck.

**Comment by rdkgit** [comment]
I managed to out monkey Xcode and this linker error.  Through a combination of pod updates, explicitly adding the sf-ios pod in my podfile and then re-initializing re-installing the pods, the linker error went away and I was able to successfully build and link my app.  Very strange.

**Comment by rdkgit** [comment]
Just a follow up.  In the swift file that I am calling MGRS code, I added the following lines and that seems to have helped the linker resolve the symbols:

import mgrs_ios
import grid_ios
import sf_ios

**Comment by rdkgit** [comment]
OK.  More comments on this.  Setting Build Active Architecture Only = No for all the Pods and for the project helped eliminate occasional linker errors.  Also, Pods Build Options Allow Multiplatform Builds = Yes also helps.
However, when I go to build for generic Arm64, still get linker errors.

**Comment by rdkgit** [comment]
Well, I spoke too soon.  I am now getting undefined symbol SFGeometryUtils when I build my project with the mgrs-ios cocoa pod.  I can't build anything for real devices nor simulators.  There must be some sort of build/linker setting that is breaking this.

**Comment by bosborn** [comment]
I updated my environment and couldn't duplicate.

macOS: 13.3.1 (a)
CocoaPods : 1.12.1
MGRS iOS: 1.1.4
Xcode: 14.3
Emulator: iPhone 14 Pro
iOS Version: 16.4

We usually only include the top level library and the dependencies are pulled automatically:

`pod 'mgrs-ios', '~> 1.1.4'`

You could try updating and manually cleaning if you haven't:

```
pod repo update

rm -rf Pods
rm Podfile.lock 
rm -rf *.xcworkspace

pod install
```

I was able to build and run the tests on this library.  Running the [embedded app](https://github.com/ngageoint/mgrs-ios/tree/master/app) worked as well.

I built the [develop branch on our MapCache app](https://github.com/ngageoint/geopackage-mapcache-ios/tree/develop) and after a few non related changes (min deployment versions and one non void method with no return), it worked as well for MGRS.  [Podfile dependency](https://github.com/ngageoint/geopackage-mapcache-ios/blob/0fec48f6b7418e9f49e49dfc676b507b88c13e1f/Podfile#L9).  Possibly some things you could compare against from that project's usage.

Similarly, the [develop branch of our MAGE app](https://github.com/ngageoint/mage-ios/tree/develop) built and ran without issue. [Podfile dependency](https://github.com/ngageoint/mage-ios/blob/92456c50fc058ace43f02790b8df5278f2708d1f/Podfile#L23)

**Comment by rdkgit** [comment]
Hi!

No luck.  Cleaned everything out except my own code, re did pod
install, and still get linker error.

Can you email me your xcworkspace file so I can diff them?

Wonder if there is some sorta minor diff due to me using the tiff-ios
in addition to mgrs-ios.

Thank you,

Bobby

**Comment by rdkgit** [comment]
Hi!

Should the mgrs-ios swift code import the sf-ios bridging header?

Bobby

**Comment by bosborn** [comment]
[Marlin](https://github.com/ngageoint/marlin-ios) is another iOS app example that uses mgrs-ios and is a purely Swift app.  You should be able to clone, build, run, and compare against the workspace.

**Comment by rdkgit** [comment]
Yikes!!  I deleted the bridging header file from my project and am still running into the same linker error.  I'll re-download my repo again and remove the bridging header file and see if I can build.  Hmmm.

**Comment by bosborn** [comment]
It needs to be removed from the project itself, not just the file.

![image](https://github.com/ngageoint/mgrs-ios/assets/11667761/d24be84f-cc5e-4c01-b5a7-7ddd3f3174cc)

**Comment by rdkgit** [comment]
So, something must be messed up in my Xcode environment then because I removed the bridging header file from the git repo that I re-downloaded and I still get the linker error.  At this point, not sure if I should re-install Xcode.  Really weird.

**Comment by bosborn** [comment]
[OpenAthenaIOS-main.zip](https://github.com/ngageoint/mgrs-ios/files/11502307/OpenAthenaIOS-main.zip)

**Comment by rdkgit** [comment]
Hey!  Thank you for your help.  I downloaded your OpenAthenaIOS-main.zip file and it still fails to build on my system.  At this point, I think I uninstall Xcode and re-install?  I don't see any other option.

**Comment by bosborn** [comment]
I guess so.  Try closing Xcode, manually cleaning that zip, and rebuild.

```
rm -rf Pods
rm Podfile.lock 
rm -rf *.xcworkspace

pod install
```
